import Foundation

public let 🀇 = 1.萬!
public let 🀈 = 2.萬!
public let 🀉 = 3.萬!
public let 🀊 = 4.萬!
public let 🀋 = 5.萬!
public let 🀌 = 6.萬!
public let 🀍 = 7.萬!
public let 🀎 = 8.萬!
public let 🀏 = 9.萬!
public let 🀐 = 1.索!
public let 🀑 = 2.索!
public let 🀒 = 3.索!
public let 🀓 = 4.索!
public let 🀔 = 5.索!
public let 🀕 = 6.索!
public let 🀖 = 7.索!
public let 🀗 = 8.索!
public let 🀘 = 9.索!
public let 🀙 = 1.筒!
public let 🀚 = 2.筒!
public let 🀛 = 3.筒!
public let 🀜 = 4.筒!
public let 🀝 = 5.筒!
public let 🀞 = 6.筒!
public let 🀟 = 7.筒!
public let 🀠 = 8.筒!
public let 🀡 = 9.筒!
public let 🀀 = Tile.east
public let 🀁 = Tile.south
public let 🀂 = Tile.west
public let 🀃 = Tile.north
public let 🀄 = Tile.center
public let 🀅 = Tile.fortune
public let 🀆 = Tile.blank

public let 一萬 = 1.萬!
public let 二萬 = 2.萬!
public let 三萬 = 3.萬!
public let 四萬 = 4.萬!
public let 五萬 = 5.萬!
public let 六萬 = 6.萬!
public let 七萬 = 7.萬!
public let 八萬 = 8.萬!
public let 九萬 = 9.萬!
public let 一筒 = 1.筒!
public let 二筒 = 2.筒!
public let 三筒 = 3.筒!
public let 四筒 = 4.筒!
public let 五筒 = 5.筒!
public let 六筒 = 6.筒!
public let 七筒 = 7.筒!
public let 八筒 = 8.筒!
public let 九筒 = 9.筒!
public let 一索 = 1.索!
public let 二索 = 2.索!
public let 三索 = 3.索!
public let 四索 = 4.索!
public let 五索 = 5.索!
public let 六索 = 6.索!
public let 七索 = 7.索!
public let 八索 = 8.索!
public let 九索 = 9.索!
public let 東: Tile = .east
public let 西: Tile = .west
public let 南: Tile = .south
public let 北: Tile = .north
public let 白: Tile = .blank
public let 發: Tile = .fortune
public let 中: Tile = .center

public let MarjongTileCharacterSet = { () -> CharacterSet in
    let start = Character("🀀").unicodeScalars.first!
    let end = Character("🀫").unicodeScalars.first!
    let range: ClosedRange<Unicode.Scalar> = start...end
    return CharacterSet(charactersIn: range)
}()
